### ISSUE TITLE
Cannot load contract

### ISSUE THREAD

**Issue by PatrickAlphaC** [vyperlang/titanoboa#342] opened 2024-11-14 19:21 UTC
```bash
>>> import boa
>>> boa.load("favorites.vy")
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    boa.load("favorites.vy")
    ~~~~~~~~^^^^^^^^^^^^^^^^
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/interpret.py", line 177, in load
    return loads(f.read(), *args, name=name, **kwargs, filename=filename)
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/interpret.py", line 189, in loads
    d = loads_partial(source_code, name, filename=filename, compiler_args=compiler_args)
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/interpret.py", line 252, in loads_partial
    return _loads_partial_vvm(source_code, version, filename)
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/interpret.py", line 286, in _loads_partial_vvm
    return _disk_cache.caching_lookup(cache_key, _compile)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/util/disk_cache.py", line 70, in caching_lookup
    res = func()
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/interpret.py", line 277, in _compile
    return VVMDeployer.from_compiler_output(compiler_output, filename=filename)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my/path/scrap/.venv/lib/python3.13/site-packages/boa/contracts/vvm/vvm_contract.py", line 41, in from_compiler_output
    abi = compiler_output["abi"]
          ~~~~~~~~~~~~~~~^^^^^^^
TypeError: string indices must be integers, not 'str'
```

`favorites.vy` is a very minimal contract.

**Comment by PatrickAlphaC** [comment] 2024-11-14 20:53
Ok weird, I found this, in the working version of `vvm.main.compile_source` you see:

```python
compiler_data = _compile(
        vyper_binary=vyper_binary,
        vyper_version=vyper_version,
        source_files=[source_path],
        base_path=base_path,
        evm_version=evm_version,
    )

    return {"<stdin>": list(compiler_data.values())[0]}
```

but the broken version is:

```python
        compiler_data = _compile(
            vyper_binary=vyper_binary,
            vyper_version=vyper_version,
            source_files=[source_file.name],
            base_path=base_path,
            evm_version=evm_version,
            output_format=output_format,
        )

    if output_format in ("combined_json", None):
        return {"<stdin>": list(compiler_data.values())[0]}
    return compiler_data
```

**Comment by PatrickAlphaC** [comment] 2024-11-14 21:04
Ah ok, more info. This only happens when the vyper version in the file does not match the vyper version of the vyper package. 

```python
    if version is not None and version != vyper.__version__:
        filename = str(filename)  # help mypy
        # TODO: pass name to loads_partial_vvm, not filename
        return _loads_partial_vvm(source_code, version, filename)
```

Seems as simple as passing more info here...

**Comment by DanielSchiavini** [comment] 2024-11-15 09:16
The code looks fine. As a matter of fact, it runs in the test pipeline: https://github.com/vyperlang/titanoboa/blob/a52c79c67ba0e00ceafc70f9daf730c9a57f27c9/tests/unitary/contracts/vvm/test_vvm.py#L25

I cannot reproduce the issue you are experiencing.

**Comment by trocher** [comment] 2024-11-19 13:29
Fixed in vvm, will be reflected in titanoboa once it uses a vvm version including the patch. https://github.com/vyperlang/vvm/pull/29

**Closed** 2024-11-22 09:10 UTC
