### ISSUE TITLE
Transient storage is persisting

### ISSUE THREAD

**Issue by sajal** [vyperlang/titanoboa#216] opened 2024-05-10 09:49 UTC
I'm not sure if this is a bug with boa, or pyevm, or that I'm doing something silly., here is the py-evm bug report ethereum/py-evm#2177

Basically at end of transaction, transient storage is not being reset.

py-evm==0.10.1b1
titanoboa @ git+https://github.com/vyperlang/titanoboa@4eaa59e6c4d884e6280e0d970e566044271942a6

Reproduce step:

```python
import boa

def test_transient():
    cont = boa.loads("""
#pragma version 0.3.10
#pragma optimize codesize
#pragma evm-version cancun
cache: transient(uint256)
              
@external
def __init__():
    pass

@external
@nonpayable
def set(num: uint256):
    self.cache = num

@external
@nonpayable
def get() -> uint256:
    return self.cache
            """)
    
    assert cont.get() == 0
    cont.set(100)
    assert cont.get() == 0
```

**Comment by charles-cooper** [comment] 2024-05-10 11:39
it's expected behavior, not a bug. titanoboa executes all code within a single transaction context. the correct thing you want to do is call `clear_transient_storage()` in between contract calls, but we didn't add any machinery to titanoboa yet to do it.

closing this since it's not really a bug, but you can keep commenting here if you still need help.

**Closed by charles-cooper** 2024-05-10 11:39 UTC

**Comment by sajal** [comment] 2024-05-10 11:58
This could be problematic.

Since we use transient storage as a cache, we now need to add command to flush it after each operation, which we can do because its our own contract in Vyper, however our goal is to have a lot of tests integrating with external protocols (in a forked network), we have low visibility into these protocols who may or maynot be using transient storage themselves, and the values not resetting will cause a lot of hard-to-debug issues in the future.

**Comment by charles-cooper** [comment] 2024-05-10 12:03
this is by design - you have a higher guarantee of correctness from testing if you are forced to work against the assumption that each call is isolated in a single transaction. in real EVM, you don't have this guarantee, so IMO your tests should not bake in the assumption.

**Comment by sajal** [comment] 2024-05-10 12:36
> you have a higher guarantee of correctness from testing if you are forced to work against the assumption that each call is isolated in a single transaction

Thats fair, however in our contract, during the transaction, we invalidate the transient cache whenever we expect it to change. This issue only manifested itself because in my test I time traveled to the future, it wouldn't have been an issue if it was in a subsequent call within the same tx (or same block even).

Perhaps consider a feature to flush transient if we time travel?

**Comment by charles-cooper** [comment] 2024-05-10 13:00
> > you have a higher guarantee of correctness from testing if you are forced to work against the assumption that each call is isolated in a single transaction
> 
> Thats fair, however in our contract, during the transaction, we invalidate the transient cache whenever we expect it to change. This issue only manifested itself because in my test I time traveled to the future, it wouldn't have been an issue if it was in a subsequent call within the same tx (or same block even).
> 
> Perhaps consider a feature to flush transient if we time travel?

that's a good idea. can you create an issue for this? i think there are some edge cases, like what happens if you travel backwards to a previous block.

**Comment by sajal** [comment] 2024-05-10 13:37
Will do. BTW I didn't realize backwards time travel was possible!

**Comment by charles-cooper** [comment] 2024-05-10 13:43
> Will do. BTW I didn't realize backwards time travel was possible!

yes, it is, and in fact maybe we should ban it in the high level api :smiling_face_with_tear:

**Comment by Findmycrypto** [comment] 2024-09-06 09:54
I believe when I took the original amount of Trump maga when at around 3.37 or so I got 113 shares sent to my base accounts I still have contract hash from original start then I had not a clue what I was doing when it said don't send back to coinbase that I added it to metamask which it disappeared from when the app crashed so the endpoint was self destructed and reconstructed on the ETH chain I bridged through metamask from base. I watched my balance only on the wallet and then out of nowhere it gets sent by an evm to the contract address and I was baffled no idea what to do and have tried all but giving up on crypto seems it's too complicated for the average and make one misstep unknowingly then guess you're just robbed on a blockchain where I would assume when I put in SRP added accounts back so would my maga trump tokens but they never did I know the address they sit in they're my tokens and I've exhausted myself trying to understand with everything saved block #'s details the json file the npm file and cvs reports I could just have done proved I am not lying it's ky asset but no one in any direction cares I lost 1500 in profit on those shares when it blew to 18.00 per a month or two back it was purchased end March or April 1-4th I signed a contract that no I didn't save my signature hash went about my life all until I bridged it and ever since it's been nothing but ridiculous and so time consuming and confusing to me completely so if I'm ever allowed to have my assets returned to me I would like them sent back to which address they were originally bought from which they hopped from this protocol to that to wbtc back to maga then we're fine except i didn't understand my base wallet would have been just fine too 😓😞😴
Sanchi Hancock
Asset Maga Trump 112. Some number I don't have written down but could easily pull up as well as my bridged out and bridged in transactions on my transactions history. I'm stunned it's this complicated and as pro crypto as I am they've taken and made it so easy to get scammed and robbed blind that it may not be the new currency we hoped it could also way down from 74k to 55k today smdh. Let me know if knowing all the context to this months and months longs of sad attempt to recover my asset and never could 😴
Sunni or Sunnis shit are tags I've put on some of the transactions I couldn't tell which from what
